# Generated by Django 4.2.7 on 2025-12-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dst_ip", models.GenericIPAddressField(db_index=True)),
                (
                    "proto",
                    models.CharField(
                        choices=[
                            ("TCP", "TCP"),
                            ("UDP", "UDP"),
                            ("ICMP", "ICMP"),
                            ("HTTP", "HTTP"),
                            ("HTTPS", "HTTPS"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=10,
                    ),
                ),
                ("packet_size", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("block", "Block"), ("drop", "Drop")],
                        max_length=10,
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(blank=True, help_text="Additional raw log data", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "network_logs",
                "ordering": ["-timestamp", "-created_at"],
                "indexes": [
                    models.Index(fields=["timestamp"], name="network_log_timesta_bb9a45_idx"),
                    models.Index(fields=["src_ip"], name="network_log_src_ip_b70823_idx"),
                    models.Index(fields=["dst_ip"], name="network_log_dst_ip_984acb_idx"),
                ],
            },
        ),
    ]
