# Generated by Django 4.2.7 on 2025-12-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("port_scan", "Port Scan"),
                            ("brute_force", "Brute Force"),
                            ("ddos", "DDoS Attack"),
                            ("malware", "Malware Detection"),
                            ("suspicious_traffic", "Suspicious Traffic"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dst_ip", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(blank=True, help_text="Additional alert metadata", null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-timestamp", "-created_at"],
            },
        ),
    ]
