# Generated by Django 4.2.7 on 2025-12-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["status", "severity"], name="alerts_status_5203b6_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["alert_type"], name="alerts_alert_t_eda531_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["timestamp"], name="alerts_timesta_67be6b_idx"),
        ),
    ]
