# Generated by Django 4.2.7 on 2025-12-12 18:32

import apps.ml.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("file_ref", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                (
                    "metrics",
                    models.JSONField(blank=True, help_text="Model performance metrics", null=True),
                ),
                (
                    "file_ref",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.ml.models.model_file_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ml_models",
                "ordering": ["-uploaded_at"],
                "unique_together": {("name", "version")},
            },
        ),
    ]
