# Generated by Django 4.2.7 on 2026-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "suspicious_traffic_threshold",
                    models.IntegerField(
                        default=100,
                        help_text="Max requests per minute before flagging as suspicious",
                    ),
                ),
                (
                    "port_scan_limit",
                    models.IntegerField(
                        default=20, help_text="Number of port scans to trigger alert"
                    ),
                ),
                (
                    "failed_login_limit",
                    models.IntegerField(
                        default=5, help_text="Failed login attempts before lockout/alert"
                    ),
                ),
                (
                    "packet_size_threshold",
                    models.IntegerField(
                        default=10000, help_text="Packet size (bytes) threshold for alerts"
                    ),
                ),
                (
                    "monitoring_window_minutes",
                    models.IntegerField(
                        default=5, help_text="Time window (minutes) for threshold evaluation"
                    ),
                ),
                ("email_alerts_enabled", models.BooleanField(default=True)),
                ("sms_alerts_enabled", models.BooleanField(default=False)),
                (
                    "admin_email",
                    models.EmailField(
                        default="admin@secupi.local",
                        help_text="Email address for alert notifications",
                        max_length=254,
                    ),
                ),
                (
                    "alert_severity_filter",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Minimum severity level to trigger notifications",
                        max_length=20,
                    ),
                ),
                (
                    "default_action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        default="allow",
                        help_text="Default firewall action for unmatched traffic",
                        max_length=10,
                    ),
                ),
                (
                    "log_blocked_traffic",
                    models.BooleanField(default=True, help_text="Log all blocked/denied traffic"),
                ),
                (
                    "auto_block_suspicious_ip",
                    models.BooleanField(
                        default=False, help_text="Automatically block IPs flagged as suspicious"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        default=30, help_text="Session timeout duration in minutes"
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(default=90, help_text="Number of days to retain logs"),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable two-factor authentication"
                    ),
                ),
                (
                    "live_monitoring_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable real-time traffic monitoring"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
