# Generated by Django 4.2.7 on 2025-12-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "src",
                    models.CharField(help_text="Source IP or CIDR (use * for all)", max_length=255),
                ),
                (
                    "dst",
                    models.CharField(
                        help_text="Destination IP or CIDR (use * for all)", max_length=255
                    ),
                ),
                (
                    "proto",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP"), ("ICMP", "ICMP"), ("*", "All")],
                        default="*",
                        max_length=10,
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        help_text="Port number or range (use * for all)", max_length=50
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("block", "Block"), ("drop", "Drop")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firewall_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "firewall_rules",
                "ordering": ["-created_at"],
            },
        ),
    ]
